import Navbar from './components/Navbar/Navbar.jsx'
import { useState } from 'react';
import './index.css'
import Footer from './components/Footer/Footer.jsx';

function App() {
  const [theme, setTheme] = useState('light'); 


  return (
    
    <div className={`container ${theme}`}>
      <Navbar theme={theme} setTheme={setTheme}/>
      <p>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates ab, eaque vel dolorem ducimus, eligendi est non officia nemo ratione libero ut, architecto dignissimos officiis nostrum eum obcaecati sapiente veritatis! Quos non est commodi nemo voluptatem numquam distinctio sint harum reprehenderit natus, quibusdam debitis, delectus excepturi! Amet autem nostrum, molestias reiciendis magni quo adipisci fuga ad quam recusandae necessitatibus cupiditate distinctio omnis ea rem placeat, fugit veniam impedit. Dolores doloremque quis eveniet quidem! Doloribus, at nulla, numquam quod aliquam enim atque expedita modi, provident error fugiat vel distinctio quisquam molestias hic. Incidunt, dignissimos cum. Modi minus asperiores est architecto quis!lorem300
      Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis animi perferendis earum sint accusamus, eveniet ipsa fugit, necessitatibus cum ducimus velit delectus ea ex iste fuga id incidunt? Officiis nesciunt fuga veritatis, amet omnis minima doloribus necessitatibus fugiat qui, eum, sunt ipsum magnam quisquam eligendi dolorem hic itaque iure repudiandae ducimus? Fugit, nemo ab aperiam quibusdam quidem voluptate officiis necessitatibus dignissimos repellat optio adipisci expedita tempore iusto! Iste excepturi vel dolor sed beatae ducimus quia aut, ipsum sapiente placeat quasi culpa fugit, et voluptatibus, neque aliquam corporis ut laborum maiores soluta eum voluptatem? Dolorum nobis sed sint culpa magnam neque nemo in! Ea dolores deleniti cum voluptas rem officiis maiores provident soluta. Autem hic non nulla repellat. Dignissimos optio itaque saepe voluptatum tempora, harum unde, ipsa maxime perspiciatis, praesentium eius dolorum. A, nisi. Aliquam magni perferendis eius eum nesciunt, necessitatibus, magnam unde, qui cumque iste neque quidem quis quaerat facere? Suscipit incidunt illum reprehenderit odio maiores ut natus! Mollitia pariatur, assumenda totam possimus vitae obcaecati quam itaque. Soluta, sint mollitia error ut natus, aspernatur praesentium earum fugiat adipisci iusto culpa consequuntur quas doloribus deserunt animi? Enim optio ducimus repellat corrupti, veniam sequi. Impedit velit consequuntur itaque nam amet sapiente. Iure illo quaerat voluptatum quisquam laboriosam aspernatur ipsam sint, aut quos minus ullam soluta odit amet, sed id commodi unde ab. Veritatis incidunt quam inventore eveniet facere voluptas id numquam atque rerum repellat, sit, quibusdam animi illo aliquid dolorem quis quisquam suscipit odio sed rem architecto. Aliquam doloribus nisi nesciunt? Rerum sed quaerat neque pariatur illo cum expedita iste sit, fugiat ea necessitatibus voluptas deleniti eius officiis atque sapiente itaque enim. Incidunt voluptatum dolore veritatis excepturi praesentium aperiam omnis? Reprehenderit, nemo nobis earum in facilis error quibusdam impedit qui eligendi asperiores pariatur laudantium explicabo. Praesentium neque, eveniet fugiat repudiandae sequi recusandae?
      Placeat officia temporibus vel, esse ut nulla, tenetur neque maxime, quis commodi quia eaque iusto molestias? Expedita doloribus commodi culpa ipsam quo repellendus doloremque cumque quidem quod velit perspiciatis sint voluptatum cupiditate illum, quasi dicta modi recusandae vero aliquid, animi voluptates odit ea exercitationem! Delectus voluptates laborum nesciunt esse, consequatur dolores libero tenetur adipisci quae beatae deserunt accusamus tempora ad! Quam rem sed unde placeat, ratione corporis tempora deserunt exercitationem sit harum maiores optio ducimus quod accusamus esse ad molestias voluptatem ipsum illum maxime officiis, rerum dolorem iusto! Vitae, neque eveniet totam, praesentium facere iste doloribus ab nostrum expedita similique eos laboriosam error dolore natus a mollitia! Porro voluptate, repellendus similique autem reiciendis fuga recusandae illum facilis nulla tenetur fugiat itaque! Porro dolorem sint, nesciunt nobis nulla voluptatibus natus nihil impedit nam esse labore vitae iste unde cupiditate eum facere id incidunt ipsa, debitis, sapiente repellat tempora aut voluptatum minus. Voluptatibus aperiam nostrum odio pariatur aliquam maiores animi minus, veniam dolore asperiores culpa corrupti nesciunt. Deleniti eveniet eum obcaecati rerum recusandae esse facilis sit totam sapiente, minima quis, sequi quo repudiandae eaque sed corrupti consectetur laboriosam officia ipsa quae officiis quibusdam eius? Earum voluptates magnam aperiam accusantium quas est at a, eos veritatis eius voluptatem minus esse incidunt, harum ipsa enim sapiente! Ex magni esse officiis architecto quaerat reprehenderit. Maxime consequuntur cupiditate eveniet quisquam maiores perspiciatis ratione recusandae incidunt harum. Culpa rem consequuntur numquam iure repudiandae, dolorum facere nulla similique corporis, dolore fuga quasi blanditiis error eum aliquid. Est illo ab, vel obcaecati libero magni id animi doloribus, architecto laborum praesentium eius tenetur laboriosam sapiente culpa neque accusamus cum numquam. Cumque animi quidem, in officiis placeat numquam voluptatibus facilis officia dolor blanditiis eligendi esse, optio incidunt tenetur dolores alias pariatur error voluptas!
      </p>
      <Footer theme={theme} setTheme={setTheme}/>
    </div>
  )
}

export default App
